import { useAppStore } from '@/store/useAppStore'
import { FeedbackCard } from '@/components/ui/FeedbackCard'
import { ProgressBar } from '@/components/ui/ProgressBar'
import { Badge } from '@/components/ui/Badge'
import { clsx } from 'clsx'
import { Play, Square, Activity, ShieldAlert, Save } from 'lucide-react'

/**
 * SessionPage (Real-Only Version)
 * Monitors game events in real-time. No mock data or simulations.
 */
export function SessionPage() {
  const {
    session,
    startAnalysis,
    resetSession,
    finishAnalysis,
    setActivePage,
  } = useAppStore()

  const handleStart = () => {
    resetSession()
    startAnalysis()
  }

  const handleFinish = () => {
    // Finalize the session and move to report
    // Since we are now in "Real Mode", finishAnalysis will soon be handled by the Backend match end event.
    // For now, this manually triggers the current results view.
    finishAnalysis(null as any) // We use null because the real report will be fetched by ID
    setActivePage('report')
  }

  const isIdle = session.status === 'idle'
  const isAnalyzing = session.status === 'analyzing'
  const isDone = session.status === 'done'

  return (
    <div className="h-full overflow-hidden flex flex-col">
      {/* Header */}
      <div className="p-6 border-b border-border-subtle bg-surface flex items-center justify-between">
        <div className="flex items-center gap-4">
          <div className={clsx(
            'w-10 h-10 rounded-full flex items-center justify-center animate-pulse-slow',
            isAnalyzing ? 'bg-primary/20 text-primary shadow-glow-primary' : 'bg-surface-raised text-text-tertiary'
          )}>
            <Activity size={20} />
          </div>
          <div>
            <h1 className="text-title text-text-primary">Sessão de Análise Live</h1>
            <p className="text-caption text-text-secondary">
              {isIdle ? 'Aguardando início...' : isAnalyzing ? 'Capturando dados do jogo...' : 'Análise concluída'}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          {isIdle && (
            <button onClick={handleStart} className="btn-primary gap-2">
              <Play size={14} /> Iniciar Captura
            </button>
          )}
          {isAnalyzing && (
            <button onClick={handleFinish} className="btn-danger gap-2">
              <Square size={14} /> Parar Análise
            </button>
          )}
          {isDone && (
            <button onClick={() => setActivePage('report')} className="btn-success gap-2 shadow-glow-success">
              <Save size={14} /> Ver Relatório Final
            </button>
          )}
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 grid grid-cols-5 overflow-hidden">

        {/* Left — Feedbacks Log (Generated by AI) */}
        <div className="col-span-3 border-r border-border-subtle flex flex-col overflow-hidden bg-bg-primary">
          <div className="p-4 border-b border-border-subtle flex items-center justify-between bg-surface/30">
            <span className="section-title">Insights Gerados em Tempo Real</span>
            <Badge severity="info" label={`${session.feedbacks.length} detecções`} />
          </div>

          <div className="flex-1 overflow-y-auto p-4 flex flex-col gap-3">
            {session.feedbacks.length === 0 && (
              <div className="h-full flex flex-col items-center justify-center text-center opacity-40">
                <ShieldAlert size={48} className="mb-4 text-text-tertiary" />
                <p className="text-subtitle font-medium">Nenhum feedback ainda</p>
                <p className="text-caption">Inicie a captura e comece a jogar CS2</p>
              </div>
            )}

            {session.feedbacks.map((fb) => (
              <FeedbackCard key={fb.id} feedback={fb} />
            ))}
          </div>
        </div>

        {/* Right — Technical Event Log */}
        <div className="col-span-2 flex flex-col overflow-hidden bg-bg-secondary">
          <div className="p-4 border-b border-border-subtle flex items-center justify-between bg-surface/30">
            <span className="section-title">Log de Eventos (Real-time)</span>
          </div>

          {/* Progress Bar */}
          <div className="px-4 py-3 bg-surface/50 border-b border-border-subtle">
            <ProgressBar
              value={session.progress}
              label={session.current_step || (isAnalyzing ? 'Ouvindo eventos do jogo...' : 'Aguardando partida...')}
              animated={isAnalyzing}
              size="sm"
            />
          </div>

          <div className="flex-1 overflow-y-auto p-4 font-mono text-[11px] flex flex-col gap-1.5"
               ref={(el) => { if (el) el.scrollTop = el.scrollHeight }}>
            {session.events.length === 0 && isAnalyzing && (
              <p className="text-text-tertiary italic">Listening for Game State Integration (GSI)...</p>
            )}
            {session.events.slice().reverse().map((ev) => (
              <div key={ev.id} className="flex gap-2 animate-fade-in group">
                <span className="text-text-tertiary group-hover:text-primary transition-colors">[{new Date(ev.timestamp).toLocaleTimeString()}]</span>
                <span className="text-primary font-bold">{ev.type}</span>
                <span className="text-text-secondary truncate">{JSON.stringify(ev.payload)}</span>
              </div>
            ))}
          </div>

          {/* HUD Info */}
          <div className="p-4 border-t border-border-subtle bg-surface/50">
            <div className="flex items-center gap-3 p-3 rounded-lg border border-primary/20 bg-primary/5">
              <div className="p-2 rounded bg-primary/10 text-primary">
                <Activity size={16} />
              </div>
              <div>
                <p className="text-caption-xs font-bold text-primary uppercase tracking-widest">Coaching Ativo</p>
                <p className="text-caption text-text-secondary">Os alertas críticos são processados instantaneamente.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
