import { useEffect, useState, useRef } from 'react'
import { useAppStore } from '@/store/useAppStore'
import { FeedbackCard } from '@/components/ui/FeedbackCard'
import { ProgressBar } from '@/components/ui/ProgressBar'
import { Badge } from '@/components/ui/Badge'
import { MOCK_FEEDBACKS, MOCK_REPORT } from '@/services/mockData'
import { clsx } from 'clsx'
import { Play, Square, Activity, ShieldAlert, Save } from 'lucide-react'

// Simulation events sequences
const EVENT_STREAM = [
  { type: 'MatchStarted', payload: { map: 'de_dust2', mode: 'Competitive' }, delay: 500 },
  { type: 'RoundStarted', payload: { round: 1 }, delay: 1500 },
  { type: 'PlayerPositioned', payload: { x: 120, y: 450, z: 10 }, delay: 2000 },
  { type: 'CrosshairMoved', payload: { pitch: 12.5, yaw: 45.2 }, delay: 2500 },
  { type: 'FeedbackGenerated', payload: MOCK_FEEDBACKS[0], isFeedback: true, delay: 3000 }, // Crosshair low
  { type: 'PlayerKilled', payload: { victim: 'FabrizioCS', weapon: 'ak47', is_headshot: true }, delay: 4500 },
  { type: 'FeedbackGenerated', payload: MOCK_FEEDBACKS[1], isFeedback: true, delay: 5000 }, // Bad reload
  { type: 'RoundEnded', payload: { winner: 'T', reason: 'target_bombed' }, delay: 6500 },
  { type: 'RoundStarted', payload: { round: 2 }, delay: 8000 },
  { type: 'UtilityUsed', payload: { type: 'flashbang', effectiveness: 0.2 }, delay: 9500 },
  { type: 'FeedbackGenerated', payload: MOCK_FEEDBACKS[2], isFeedback: true, delay: 10500 }, // Death no util
  { type: 'MatchEnded', payload: { winner: 'CT', score: '16-11' }, delay: 12000 },
]

export function SessionPage() {
  const {
    session,
    startAnalysis,
    resetSession,
    pushEvent,
    addFeedback,
    updateSessionProgress,
    finishAnalysis,
    setActivePage,
  } = useAppStore()

  const [, setSimIndex] = useState(-1)
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const stopSim = () => {
    if (timerRef.current) clearTimeout(timerRef.current)
    setSimIndex(-1)
  }

  const runSimStep = (index: number) => {
    if (index >= EVENT_STREAM.length) {
      updateSessionProgress(100, 'Análise finalizada')
      return
    }

    const step = EVENT_STREAM[index]
    timerRef.current = setTimeout(() => {
      if (step.isFeedback) {
        addFeedback(step.payload)
      } else {
        pushEvent(step.type, step.payload)
      }

      const progress = Math.round(((index + 1) / EVENT_STREAM.length) * 100)
      updateSessionProgress(progress, `Processando: ${step.type}`)
      setSimIndex(index)
      runSimStep(index + 1)
    }, step.delay - (index > 0 ? EVENT_STREAM[index - 1].delay : 0))
  }

  const handleStart = () => {
    resetSession()
    startAnalysis()
    setSimIndex(0)
    runSimStep(0)
  }

  const handleFinish = () => {
    stopSim()
    // @ts-ignore - Mock report might not strictly follow current API structure
    finishAnalysis(MOCK_REPORT as any)
    setActivePage('report')
  }

  useEffect(() => {
    return () => stopSim()
  }, [])

  const isIdle = session.status === 'idle'
  const isAnalyzing = session.status === 'analyzing'
  const isDone = session.status === 'done'

  return (
    <div className="h-full overflow-hidden flex flex-col">
      {/* Header */}
      <div className="p-6 border-b border-border-subtle bg-surface flex items-center justify-between">
        <div className="flex items-center gap-4">
          <div className={clsx(
            'w-10 h-10 rounded-full flex items-center justify-center animate-pulse-slow',
            isAnalyzing ? 'bg-primary/20 text-primary shadow-glow-primary' : 'bg-surface-raised text-text-tertiary'
          )}>
            <Activity size={20} />
          </div>
          <div>
            <h1 className="text-title text-text-primary">Sessão de Análise Live</h1>
            <p className="text-caption text-text-secondary">
              {isIdle ? 'Aguardando início...' : isAnalyzing ? 'Capturando dados do jogo...' : 'Análise concluída'}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          {isIdle && (
            <button onClick={handleStart} className="btn-primary gap-2">
              <Play size={14} /> Iniciar Captura
            </button>
          )}
          {isAnalyzing && (
            <button onClick={handleFinish} className="btn-danger gap-2">
              <Square size={14} /> Parar Análise
            </button>
          )}
          {isDone && (
            <button onClick={() => setActivePage('report')} className="btn-success gap-2 shadow-glow-success">
              <Save size={14} /> Ver Relatório Final
            </button>
          )}
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 grid grid-cols-5 overflow-hidden">

        {/* Left — Feedbacks Log (Generated by AI) */}
        <div className="col-span-3 border-r border-border-subtle flex flex-col overflow-hidden bg-bg-primary">
          <div className="p-4 border-b border-border-subtle flex items-center justify-between bg-surface/30">
            <span className="section-title">Insights Gerados em Tempo Real</span>
            <Badge severity="info" label={`${session.feedbacks.length} detecções`} />
          </div>

          <div className="flex-1 overflow-y-auto p-4 flex flex-col gap-3">
            {session.feedbacks.length === 0 && !isAnalyzing && (
              <div className="h-full flex flex-col items-center justify-center text-center opacity-40">
                <ShieldAlert size={48} className="mb-4 text-text-tertiary" />
                <p className="text-subtitle font-medium">Nenhum feedback ainda</p>
                <p className="text-caption">Inicie a captura para começar a análise live</p>
              </div>
            )}

            {session.feedbacks.map((fb) => (
              <FeedbackCard key={fb.id} feedback={fb} />
            ))}
          </div>
        </div>

        {/* Right — Technical Event Log */}
        <div className="col-span-2 flex flex-col overflow-hidden bg-bg-secondary">
          <div className="p-4 border-b border-border-subtle flex items-center justify-between bg-surface/30">
            <span className="section-title">Log de Eventos (Raw Feed)</span>
            <div className="flex items-center gap-3">
               <span className="text-[10px] text-text-tertiary font-mono">LIVE_TICK: 14201</span>
            </div>
          </div>

          {/* Progress Bar */}
          <div className="px-4 py-3 bg-surface/50 border-b border-border-subtle">
            <ProgressBar
              value={session.progress}
              label={session.current_step || 'Aguardando dados...'}
              animated={isAnalyzing}
              size="sm"
            />
          </div>

          <div className="flex-1 overflow-y-auto p-4 font-mono text-[11px] flex flex-col-reverse gap-1.5">
            {session.events.length === 0 && (
              <p className="text-text-tertiary italic">Listening for game state integration...</p>
            )}
            {session.events.map((ev) => (
              <div key={ev.id} className="flex gap-2 animate-fade-in group">
                <span className="text-text-tertiary group-hover:text-primary transition-colors">[{new Date(ev.timestamp).toLocaleTimeString()}]</span>
                <span className="text-primary font-bold">{ev.type}</span>
                <span className="text-text-secondary truncate">{JSON.stringify(ev.payload)}</span>
              </div>
            ))}
          </div>

          {/* HUD Simulator info */}
          <div className="p-4 border-t border-border-subtle bg-surface/50">
            <div className="flex items-center gap-3 p-3 rounded-lg border border-primary/20 bg-primary/5">
              <div className="p-2 rounded bg-primary/10 text-primary">
                <Activity size={16} />
              </div>
              <div>
                <p className="text-caption-xs font-bold text-primary uppercase tracking-widest">Overlay Ativo</p>
                <p className="text-caption text-text-secondary">Os alertas críticos estão sendo enviados ao seu HUD in-game.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
