name: "Sync to Main Repo"

on:
  push:
    branches:
      - main

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.SYNC_TOKEN }}
          repository: fbzsaullo/Stratify
          event-type: update-client
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
